version: "3.5"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - database:/var/lib/mysql
    networks:
      - network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    env_file:
      - .env
    depends_on:
       -  mariadb
    restart: always
    volumes:
      - files:/var/www/html
    networks:
      - network
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    env_file: 
      - .env
    restart: always
    depends_on:
      - mariadb
    volumes:
      - files:/var/www/html
    ports:
      - "443:443"
    networks:
      - network

volumes:
  files:
    driver_opts:
      type: none
      device: "/home/maroly/data/files"
      o: bind
  database:
    driver_opts:
      type: none
      device: "/home/maroly/data/database"
      o: bind
    
networks:
  network:
    name: network
    driver: bridge
